name: M3U8_ACTION

on:
  push:
    branches:
    - feature/main-workflow

jobs:

  m3u8_action:
    name: m3u8_action
    runs-on: "ubuntu-latest"

    steps:

      - name: Setup Environment
        # e.g. create work dirst, store in env variables ... https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions
        run: |
          echo "IPTVCAT_DATE=$(date -d "yesterday 13:00" '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "IPTVCAT_DOWNLOAD_DIR=${{ github.workspace }}/temp/iptvcat" >> $GITHUB_ENV
          echo "M3U8_DIR=${{ github.workspace }}temp/m3u8" >> $GITHUB_ENV

      - name: Setup Dirs
        run: |
          echo "IPTVCAT_DATE: '${IPTVCAT_DATE}'"
          echo "IPTVCAT_DOWNLOAD_DIR: '${IPTVCAT_DOWNLOAD_DIR}'"
          echo "M3U8_DIR: '${M3U8_DIR}'"

          echo "Command: 'mkdir -p ${IPTVCAT_DOWNLOAD_DIR}'"
          mkdir -p ${IPTVCAT_DOWNLOAD_DIR}
          echo "Command: 'mkdir -p ${M3U8_DIR}'"
          mkdir -p ${M3U8_DIR}

          echo "Command: 'ls ${IPTVCAT_DOWNLOAD_DIR}'"
          ls ${IPTVCAT_DOWNLOAD_DIR}
          echo "Command: 'ls ${M3U8_DIR}'"
          ls ${M3U8_DIR}

      - name: Get IPTVCat Release
        run: |
          echo "Command: 'scripts\iptvcat\get_iptvcat_scraper_release.sh "${IPTVCAT_DATE}" "${IPTVCAT_DOWNLOAD_DIR}"'"
          #scripts\iptvcat\get_iptvcat_scraper_release.sh "${IPTVCAT_DATE}" "${IPTVCAT_DOWNLOAD_DIR}"

      # - name: Convert IPTVCat (JSON to m3u8)

      # - name: Upload m3u8 files

